### ISSUE TITLE
RTD do not build pull requests

### ISSUE THREAD

**Issue by offtherailz** [KengoTODA/rtd-bot#242]
Hi, first of all, very good job :+1: 

I wanted to notify you that it's around a week that we don't see any comment for the build. 
This is a sample pull request that didn't triggered it : 
https://github.com/geosolutions-it/MapStore2/pull/3868

Hope it helps

**Comment by KengoTODA** [comment]
Hi @offtherailz, thanks for your contribution!

Currently this product only supports to build for the PR from branches in the same repository. Because RTD cannot fetch changes from the external repository (in your case [allyoucanmap/MapStore2](https://github.com/allyoucanmap/MapStore2/).

I [previously got the same question](https://github.com/pytest-dev/pytest/pull/4646#issuecomment-454254869), then I will create FAQ in README.md to answer this question.

**Comment by offtherailz** [comment]
Ok, understood.
Thank you very much.
